---
- name: restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes