---
- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes

- name: restart heartbeat
  systemd:
    name: heartbeat
    state: restarted
    enabled: yes

- name: restart keepalived
  systemd:
    name: keepalived.service
    state: restarted
    enabled: yes
