---
- tags:
  - kworker
  block: 
  - tags: 
    - kworker_install
    - install
    block:
    - name: Include OS Specific setup tasks
      include: setup-Debian.yml
      when: ansible_os_family == 'Debian'

    - name: Include OS Specific setup tasks
      include: setup-RedHat.yml
      when: ansible_os_family == 'RedHat'

  - include: config.yml
    tags: 
      - kworker_config
      - config


- name: Remove kworker
  include: remove.yml
  tags: 
    - "{{ 'never' if (ansible_run_tags | intersect(['remove', 'kworker_remove']) | length) == 0 else 'always' }}"