---
- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common
    - ipvsadm
    - acl

- name: add Kubernetes and Docker apt-keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://download.docker.com/linux/ubuntu/gpg"
    - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

- name: Add Kubernetes and Docker APT repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.fname }}"
  loop:
    - { repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main", fname: "kubernetes" }
    - { repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ hostvars[inventory_hostname].ansible_distribution_release }} stable", fname: "docker" }
    - { repo: "ppa:gluster/glusterfs-7", fname: "glusterfs-7"}

- name: Install packages
  apt:
    name: "{{ package }}"
    state: present
    # cache_valid_time: "{{ 0 if i == 0 else 86400 }}"
    cache_valid_time: 86400
  loop:
    - "docker-ce={{ docker_version }}"
    - "kubelet={{ kube_version }}-00"
    - "kubeadm={{ kube_version }}-00"
    - "glusterfs-client"
  loop_control:
    # index_var: i
    loop_var: "package"
  notify: restart docker

- name: Configure Docker Runtime
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: restart docker

- name: Restart docker daemon
  systemd:
    name: docker
    state: restarted