---

- tags: 
    - elasticsearch           
    - elasticsearch_install
    - elasticsearch_config
    - config
    - elasticsearch_remove
    - remove
    - elasticsearch_templates
    - elasticsearch_plugins
    - elasticsearch_xpack
  block:
  - set_fact: "es_major_version={{ es_version.split('.')[0] }}.x"
    when:
      - es_major_version is undefined

  - name: os-specific vars
    include_vars: Debian.yml
    when: ansible_os_family == 'Debian'

  - name: os-specific vars
    include_vars: RedHat.yml
    when: ansible_os_family == 'RedHat'

  - name: set compatibility variables
    include: compatibility-variables.yml

  - name: check-set-parameters
    include: elasticsearch-parameters.yml


- tags: elasticsearch
  block:
  - name: use snapshot release
    include: snapshot-release.yml
    when: es_use_snapshot_release

  - name: include java.yml
    include: java.yml
    when: es_java_install
    tags:
      - java

  - name: include elasticsearch.yml
    include: elasticsearch.yml
    tags:
      - elasticsearch_install

  - name: include elasticsearch-config.yml
    include: elasticsearch-config.yml
    tags:
      - config
      - elasticsearch_config

  - name: include elasticsearch-plugins.yml
    include: elasticsearch-plugins.yml
    when: es_plugins is defined or es_plugins_reinstall
    tags:
      - elasticsearch_plugins

  #We always execute xpack as we may need to remove features
  - name: include xpack/elasticsearch-xpack.yml
    include: xpack/elasticsearch-xpack.yml
    tags:
      - elasticsearch_xpack

  - name: include elasticsearch-ssl.yml
    include: elasticsearch-ssl.yml
    when: es_enable_http_ssl or es_enable_transport_ssl
    tags:
      - elasticsearch_xpack

  - name: flush handlers
    meta: flush_handlers

  - name: Make sure elasticsearch is started
    become: yes
    service: name=elasticsearch state=started enabled=yes
    when: es_start_service

  - name: Wait for elasticsearch to startup
    wait_for: host={{ es_api_host }} port={{ es_api_port }} delay=5 connect_timeout=1
    when: es_restarted is defined and es_restarted.changed and es_start_service

  - name: Add Fluentd template
    uri:
      url: "http://localhost:{{ elastic_data_port }}/_index_template/fluentd"
      method: PUT
      body_format: json
      body: |
        {
          "index_patterns": [ "{{ fluentd_index_name }}-*" ],
          "template": {
            "settings": {
                "number_of_replicas": {{ 0 if (groups.elastic | length) == 1 else 1 }},
                "number_of_shards": 1,
                "index.lifecycle.name": "cleanup-fluentd"
            }
          },
          "_meta": {
            "description": "Template for Fluentd logs"
          }
        }

  - name: Add Fluentd ILM
    uri:
      url: "http://localhost:{{ elastic_data_port }}/_ilm/policy/cleanup-fluentd"
      method: PUT
      body_format: json
      body: |
        {
          "policy": {
            "phases": {
              "hot": {
                "actions": {}
              },
              "delete": {
                "min_age": "{{ fluentd_inx_retention }}",
                "actions": {
                  "delete": {}
                }
              }
            }
          }
        }

  - name: set fact manage_native_realm to false
    set_fact: manage_native_realm=false

  - name: set fact manage_native_realm to true
    set_fact: manage_native_realm=true
    when:
      - es_start_service
      - es_enable_xpack
      - (es_users is defined and es_users.native is defined) or (es_roles is defined and es_roles.native is defined)

   # If playbook runs too fast, Native commands could fail as the Native Realm is not yet up
  - name: Wait {{ es_api_sleep }} seconds for the Native Realm to come up
    command: "sleep {{ es_api_sleep }}"
    when: manage_native_realm | bool

  - name: activate-license
    include: ./xpack/security/elasticsearch-xpack-activation.yml
    when: es_start_service and es_enable_xpack and es_xpack_license is defined and es_xpack_license != ''

  - name: activate-trial
    include: ./xpack/security/elasticsearch-xpack-trial-activation.yml
    when: es_start_service and es_enable_xpack and es_xpack_trial

  #perform security actions here now elasticsearch is started
  - name: include xpack/security/elasticsearch-security-native.yml
    include: ./xpack/security/elasticsearch-security-native.yml
    when: manage_native_realm | bool

  #Templates done after restart - handled by flushing the handlers. e.g. suppose user removes security on a running node and doesn't specify es_api_basic_auth_username and es_api_basic_auth_password.  The templates will subsequently not be removed if we don't wait for the node to restart.
  #We also do after the native realm to ensure any changes are applied here first and its denf up.
  - name: include elasticsearch-template.yml
    include: elasticsearch-template.yml
    when: es_templates | bool
    tags:
      - elasticsearch_templates


- name: Remove ElasticSearch
  include: elasticsearch-remove.yml
  tags: 
    - "{{ 'never' if (ansible_run_tags | intersect(['remove', 'elasticsearch_remove']) | length) == 0 else 'always' }}"

- name: Stop ElasticSearch
  systemd: 
    name: "elasticsearch"
    state: stopped
  tags:
    - "{{ 'never' if (ansible_run_tags | intersect(['stop', 'elasticsearch_stop']) | length) == 0 else 'always' }}"

- name: Start ElasticSearch
  systemd: 
    name: "elasticsearch"
    state: started
  tags:
    - "{{ 'never' if (ansible_run_tags | intersect(['start', 'elasticsearch_start']) | length) == 0 else 'always' }}"
